### ISSUE TITLE
Date objects being returned by new date method do not have the original value set

### ISSUE THREAD

**Issue by justincy** [FamilySearch/familysearch-javascript-sdk#103]
I don't know whether or not this is a problem.

**Comment by jimmyz** [comment]
Can you give an example?

**Comment by justincy** [comment]
http://jsfiddle.net/mL906m82/1/

The SDK used to return date objects that had an original value. The new
implementation in the SDK does not do this because the API doesn't return
it. We could easily add it though since we know what value was used in the
query.
