### ISSUE TITLE
getPersonSourcesQuery vs. getPersonSourceRefs/getMultiSourceDescription

### ISSUE THREAD

**Issue by stanben** [FamilySearch/familysearch-javascript-sdk#117]
It isn't clear to me the difference between using getPersonSourcesQuery or the
getPersonSourceRefs/getMultiSourceDescription pair.  Don't they accomplish the same thing?
Why would you use one approach over the other?

**Comment by justincy** [comment]
getPersonSourcesQuery makes one HTTP request. getPersonSourceRefs +
getMultiSourceDescription makes one HTTP request for the source refs then
one HTTP request for *each* source description. If a person has 5 sources
attached, getPersonSourcesQuery makes one HTTP request
while getPersonSourceRefs + getMultiSourceDescription makes 6 HTTP requests.
