### ISSUE TITLE
getSourceRefsQuery

### ISSUE THREAD

**Issue by stanben** [FamilySearch/familysearch-javascript-sdk#118]
I am currently running the 1.0 release.  I am not receiving any useful information from the `getSourcRefsQuery`. According to the description the purpose is to "Get the people, couples, and child-and-parents relationships referencing a source".

My approach:

```js
client.getPersonSourcesQuery(persId).then(function (response) {
     var sourceRefs = response.getSourceRefs();
     for (var i = 0; i < sourceRefs.length; i++) {
            var sourceRef = sourceRefs[i];
            var description = FSResponse.getSourceDescription(sourceRef.$sourceDescriptionId);
            client.getSourceRefsQuery(description.id).then(function (response) {
                var famSRefs = response.getChildAndParentsSourceRefs();
		var coupleSRefs = response.getCoupleSourceRefs();
		var personSRefs = response.getPersonSourceRefs();
     ...
```

In all the source cases, famSrefs and coupleSrefs are empty and personSRefs always has one value which is an SRef referencing back to persId;  I was hoping a census source for example would reference back to all of the relationships identified.   Am I using this function incorrectly?

**Comment by jimmyz** [comment]
Perhaps it may be helpful to provide some background information on how FamilySearch attaches census records to persons in the tree.

Each person represented in a census record has its own ID/URI. We consider this the identifier for a record persona. One of our goals is to match each persona in the historical records to a person in the family tree.

In the case where you are expecting a census source to reference back to all of the family relationships, you would not likely find a single source that references each individual in the family. You should see multiple sources that reference each individual in the family.

Does this help?

From: stanben
Reply-To: FamilySearch/familysearch-javascript-sdk
Date: Tuesday, September 8, 2015 at 1:26 PM
To: FamilySearch/familysearch-javascript-sdk
Subject: [familysearch-javascript-sdk] getSourceRefsQuery (#118)


I am currently running the 1.0 release. I am not receiving any useful information from the getSourcRefsQuery. According to the description the purpose is to "Get the people, couples, and child-and-parents relationships referencing a source".

My approach:

client.getPersonSourcesQuery(persId).then(function (response) {
var sourceRefs = response.getSourceRefs();
for (var i = 0; i < sourceRefs.length; i++) {
var sourceRef = sourceRefs[i];
var description = FSResponse.getSourceDescription(sourceRef.$sourceDescriptionId);
client.getSourceRefsQuery(description.id).then(function (response) {
var famSRefs = response.getChildAndParentsSourceRefs();
var coupleSRefs = response.getCoupleSourceRefs();
var personSRefs = response.getPersonSourceRefs();
...

In all the source cases, famSrefs and coupleSrefs are empty and personSRefs always has one value which is an SRef referencing back to persId; I was hoping a census source for example would reference back to all of the relationships identified. Am I using this function incorrectly?

**Comment by justincy** [comment]
You should pass the function the ID of a source description. It appears that you're passing the ID of a person.

**Comment by justincy** [comment]
Ignore that last comment. I was looking at the wrong line. @jimmyz is right.

**Comment by justincy** [comment]
I should add that source references are links between persons in the tree and source descriptions. Source descriptions are not the same as historical records, though sometimes they might point to a historical record.

It sounds like you want to get a list of all other persons that exist in a source that's already attached to somebody. For example, when you find a census attached to a person, you want to get a list of all other persons from that census record (perhaps to see if they have connections to the tree too). Is that correct? If so then you can't do it. FamilySearch does not allow most partners to access historical records.

**Comment by stanben** [comment]
So how do I become a partner that can get access to historical records.  Is familySearch working on a tool that will solve the research problem of visualizing which sources really agree with each other and the tree information  and which do not.  This is still a big problem which requires tedious creation of spreadsheets or some kind of diagram to see the big picture.  Until this is fixed, most patrons will continue taking duplicate names to the temple without really identifying that there is a duplicate.

**Comment by stanben** [comment]
I have recognized that each reference to a source is from the perspective of a particular person.  The trick was to find a unique id for the source that could be recognized each time it was accessed by any one of the people associated with that source.  I have achieved that generally and so have been able to reconstruct the source information for various types of source records.
