### ISSUE TITLE
getting source information

### ISSUE THREAD

**Issue by stanben** [FamilySearch/familysearch-javascript-sdk#119]
I am attempting to obtain the source information (all the identified people in a source record as well as what personal information and events that are sited) from all the sources associated with a person.
Since there does not appear to be any API that provides this information I have tried the following approach (leaving out details):

for every person that is directly related to my active person get their id: persId
client.getPersonSourcesQuery(persId).then(function (response) {
     var sourceRefs = response.getSourceRefs();
     for (var i = 0; i < sourceRefs.length; i++) {
            var sourceRef = sourceRefs[i];
            var description = FSResponse.getSourceDescription(sourceRef.$sourceDescriptionId);
            var fileUrl = srcInfo.description.about;
            $http.get(fileUrl).then(function (response) {
                   var sourceData = response.data;
                   var sourceId = getSourceId(sourceData);
                   var source = getSource(sourceId)

**Comment by justincy** [comment]
I'm sorry but we can't help you with this. FamilySearch does not allow partners to access the historical records data via an API.

**Comment by stanben** [comment]
Why?   So there is no way to provide a partner application to analyze the source information to help determine if all the sources as well as new sources are agreeing with each other?  This is as I see it the primary problem with familySearch.

**Comment by stanben** [comment]
Where does it say in the partner web site that this is not allowed?

**Comment by dovy** [comment]
*sigh* It's just how they do it.

**Comment by justincy** [comment]
I don't know if the partner's website says anything about it. 

There's a thread on FSDN that does a good job of explaining why records can't be access via an API: https://groups.google.com/a/ldsmail.net/d/msg/FSDN/zuF-fGyDuos/fO-OqooXUUoJ

**Comment by stanben** [comment]
Thanks. I read the site and watched the video.  I don't think this applies to what I am trying to do.  I am just trying to get the textual information associated with a source record that is owned by familysearch.  I am not trying to go to other websites or go to the actual historical document.  I am just trying to give a better report on the information already provided of the sources attached to a persons record.  No different than how any patron would be evaluating the person page in family search.  Just attempting to eliminate the need for writing it all down using pencil and paper.

**Comment by stanben** [comment]
In other words, from a person page, when you click on a source link it takes you to the textual summary of the source information.   This is all information created from familysearch indexing work.  This is what I am working with.

**Comment by justincy** [comment]
@stanben What you want is the indexed/extracted data. That's discussed in the page I pointed to earlier.

> the software that manages our Historical Records Archive has implemented access controls on the images of the records, but it ___has not___ implemented access controls on the extracted record data (i.e. the indexes)

**Comment by stanben** [comment]
Sounds like a problem then because I can access the meta-data to this
indexed information without even needing a clientId.  So technically this
information is already public domain isn't it?

I have already constructed this indexed source information, I am just
dealing with problems in rare cases where the unique ID I created to
identify the bundle of sources that go together was having a problem.  That
is why I was looking into the getSourceRefsQuery interface to maybe help
smooth over some of the few problems.

So, does this information need to be closed off?  How does a developer know
what can be accessed and what cannot be accessed?   The API provides low
level functions in the plumbing module to create your own API when it isn't
available does it not.

I will be vary sad to have spent months working on something that is
disallowed when the access is there.  When I asked earlier, I had the
impression that this particular API was just not implemented yet.  From my
product discription,  I should have been rejected in receiving a client-id
since access to this information is the foundation of my AP.

**Comment by justincy** [comment]
> So, does this information need to be closed off?  

I recommend contacting devsupport for an official answer.

> How does a developer know what can be accessed and what cannot be accessed?

Any endpoint listed in the [documentation](https://familysearch.org/developers/docs/api/resources) is generally available, though you'll also need to review the [certification docs](https://familysearch.org/developers/docs/certification) to find any requirements or restrictions regarding their use.

In simple terms, FamilySearch has two APIs. The first is a public API, also known as the partner or platform API, that is documented on the developer's website. The second is a private API that is [undocumented](https://groups.google.com/a/ldsmail.net/d/msg/FSDN/1nuY4zdaRVQ/FCVUdR8OsO0J) though easily discoverable because the FamilySearch website uses it.

The only method FamilySearch has for preventing use of their private APIs is the Certification program: you can't get certified and listed in the app store if you use the private API.
