### ISSUE TITLE
Cannot getPersonMatches

### ISSUE THREAD

**Issue by DebbieHoltzendorff** [FamilySearch/familysearch-javascript-sdk#122]
Testing Javscript SKD 2: Calling getPersonMatches gets 
GET https://familysearch.org/KWZ7-XVD?access_token=USYSF7A4BBFBABC8729CE104BE465BEC654B_idses-prod03.a.fsglobal.net 404 (Not Found).

My code:
var fsClient = new FamilySearch({
    client_id: 'a0T3000000BfYxfEAF',
    environment: 'production',
    redirect_uri: 'http://woodenvillage.org/Debbie'
});
.
.
.
console.log('        CALLING getPersonMatches[' + pidArray[ancCounter] + ']');
fsClient.getPersonMatches(pidArray[ancCounter]).then(function(response) …

Is this a bug in the SDK?
Thanks.

**Comment by justincy** [comment]
Nope, that's not a bug. You'll see in the [getPersonMatches()](http://familysearch.github.io/familysearch-javascript-sdk/2.0/#/api/searchAndMatch.functions:getPersonMatches) docs that it no longer accepts the PID of a person; instead it requires the full URL to the matches endpoint for that person. Why? It was a inherit side-effect of migrating from Discovery to Collections.

You can also call the `getMatches()` method directly on a Person object. It will call `getPersonMatches()` with the correct URL.

Does that help?

**Comment by DebbieHoltzendorff** [comment]
Thank you! Thank you! I missed those details.
