### ISSUE TITLE
How to getPersonMatches?

### ISSUE THREAD

**Issue by DebbieHoltzendorff** [FamilySearch/familysearch-javascript-sdk#123]
I am looking for a person's duplicates and in the old SDK used getPersonMatches[KWZ7-XVD]? But I get "Not Found" with SDK 2. Is there documentations somewhere about how to do this?

**Comment by justincy** [comment]
How is this different than your question at https://github.com/FamilySearch/familysearch-javascript-sdk/issues/122?

**Comment by DebbieHoltzendorff** [comment]
You are right. This is the same. Sorry.
