### ISSUE TITLE
README and jquery example lists wrong SDK

### ISSUE THREAD

**Issue by nickbaum** [FamilySearch/familysearch-javascript-sdk#124]
The README links to the 1.0.0 SDK on the CDN, but it seems the current version is 2.1.0:

https://github.com/FamilySearch/familysearch-javascript-sdk/blob/master/README.md

The jquery example links to the 2.0.0 SDK, but that link is no longer live:

https://github.com/FamilySearch/familysearch-javascript-sdk/blob/master/examples/jquery.html

Instead, it should link to the 2.1.0 SDK.

**Comment by marshalldan** [comment]
Thanks for bringing it to our attention. Got it current now.

**Comment by nickbaum** [comment]
Great, thanks for the quick fix!
