### ISSUE TITLE
Still true that redirect_uri doesn't need to exist?

### ISSUE THREAD

**Issue by anderspitman** [FamilySearch/familysearch-javascript-sdk#131]
Referring to docs [on this page](http://familysearch.github.io/familysearch-javascript-sdk/2.1/#/api). It indicates that `redirect_uri` simply needs to match between the browser and what's registered (ie something like 'http://locahost:8000`), but I wasn't able to get my sandbox auth to work until I made my server externally accessible to FamilySearch.

**Comment by justincy** [comment]
It is true that the path portion of the `redirect_uri` doesn't need to exist. However the host does need to exist and needs to be accessible from a browser. In testing, it only needs to be _your_ browser. When the app is released it needs to be accessible to your users.

Does that make sense?
