### ISSUE TITLE
accessing source descriptions or references is not implemented

### ISSUE THREAD

**Issue by stanben** [FamilySearch/familysearch-javascript-sdk#144]
In the 2.4 release of familysearch-javascript-sdk  the methods to module Person:
getSourceRefs() and getSources() do not work.

In the 2.4 version of familysearch-javascript-sdk.js exists the Person methods:  
 getSourceRefs: function() {
    return this.client.getPersonSourceRefs(this.getId());
  },
getSources: function() {
    return this.client.getPersonSourcesQuery(this.getId());
  }, 

The methods:  this.client.getPersonSourceRefs()  and this.client.getPersonSourcesQuery() do not exist

javascript runtime Errors are returned:
TypeError: this.client.getPersonSourceRefs is not a function
    at 26.utils.extend.getSourceRefs (http://localhost:61848/vendor/familysearch-javascript-sdk/familysearch-javascript-sdk.js:5992:24)

TypeError: this.client.getPersonSourcesQuery is not a function
    at 26.utils.extend.getSources (http://localhost:61848/vendor/familysearch-javascript-sdk/familysearch-javascript-sdk.js:6003:24)

**Comment by stanben** [comment]
This may be related:

All of the documented 2.4 javascript API's for accessing Source Descriptions and Source References:
getMultiSourceDescription(urls);
getSourceDescription(url);
getSourceRefs(url);
getSourceRefsQuery(url);
getSourcesQuery(url);
Take as a parameter a url or url[].  Where are the API's to get the url's?

**Comment by justincy** [comment]
This is definitely a bug.

While waiting for it to get fixed you should be able to do this:

```
getSourceRefs(person.getLink('source-references').href);
```

**Comment by stanben** [comment]
In the 1.0 release:
fsApi.getPersonSourcesQuery(persId).then(function (FSResponse) {
    var sourceRefs = FSResponse.getSourceRefs();
    var i, len;
    len = sourceRefs.length;
    for (i = 0; i < len; i++) {
        var description = FSResponse.getSourceDescription(sourceRef.$sourceDescriptionId);

Now in the 2.4 release:
fsApi.getPersonSourcesQuery(personFS.getLink('source-references').href).then(function (FSResponse) {
    var sourceRefs = FSResponse.getSourceRefs();
    var i, len;
    len = sourceRefs.length;
    for (i = 0; i < len; i++) {
        sourceRef.getSourceDescription().then(function (FSResponse) {
            var description = FSResponse.getSourceDescription();

If I am doing this correctly, it appears that in the 1.0 release the getPersonSourcesQuery method returns a lot more information so that for example getSourceDescription does not wait for a response but is already part of the response from getPersonSourcesQuery.  Isn't this more efficient to bundle more information into a response rather than requesting more information through another promise?  Or am I not seeing the picture?

**Comment by justincy** [comment]
Changing the link from `source-references` to `source-descriptions` should include the source descriptions in the response.

**Comment by stanben** [comment]
Thank you!  I don't see any method to get the description from the response setting to source-descriptions.   Looks like I can get it through FSResponse.getData().sourceDescriptions[0];  Should there be a method to get this?

Thanks

**Comment by justincy** [comment]
I forgot to mention that you should also change `getSourceRefs()` to `getSourcesQuery()`. That will ensure the response includes functions for accessing the source descriptions. However, I just released v2.4.2 which includes a fix for this issue so `person.getSources()` should behave as expected now.
