### ISSUE TITLE
failure in SourceDescription.getSourceRefsQuery

### ISSUE THREAD

**Issue by stanben** [FamilySearch/familysearch-javascript-sdk#146]
Running this code (stripped down), the program fails in `sourceDesc.getSourceRefsQuery()`:

```js
var personSource = function(sourceDesc) {
	sourceDesc.getSourceRefsQuery().then(function (response) {
		var personSrcRefs = response.getPersonSourceRefs();
		var coupleSrcRefs = response.getCoupleSourceRefs();
		var chPSrcRefs = response.getChildAndParentsSourceRefs();
	});
};

var getSources = function(personFS) {
	personFS.getSources().then(function (response) {
		var sourceDescs = response.getSourceDescriptions();
		var i, len;
		len = sourceDescs .length;
		for (i = 0; i < len; i++) {
			var sourceDesc = sourceDescs[i];
			personSource(sourceDesc);
		}
	});
};

var testPerson = function(persId) {
	fsApi.getPerson(persId).then(function (response) {
		var personFS = response.getPerson();
	        getSources(personFS);
	});
};
```

In familysearch-javascript-sdk.js line 7270:

```js
return this.client.getSourceRefsQuery(maybe(this.getLink('source-references-query')).href);
```

In familysearch-javascript-sdk.js line 1840:

```js
if(this.data.links && this.data.links[rel]){
```

this.data.links has no property by that name so undefined is returned.
therefore this.client.getSourceRefsQuery is passed an undefined argument

So deep in the code of In familysearch-javascript-sdk.js:

```js
Helpers.prototype.getAbsoluteUrl = function(server, path) {
  if (!this.isAbsoluteUrl(path)) {
    return server + (path.charAt(0) !== '/' ? '/' : '') + path;    <-- failure here because path is undefined
  }
  else {
    return path;
  }
};
```

Shouldn't there be a unit test for the the entire familysearch API should be used before release?
This would also make a great reference document for coding examples.

**Comment by justincy** [comment]
> Shouldn't there be a unit test for the the entire familysearch API should be used before release?
> This would also make a great reference document for coding examples.

There is a [test suites](https://github.com/FamilySearch/familysearch-javascript-sdk/tree/master/test/unit) that includes 177 tests. It is run automatically on [Travis](https://travis-ci.org/FamilySearch/familysearch-javascript-sdk) with each change. It has [86% test coverage](https://coveralls.io/builds/4458245) with a large portion of the untested code being from browser-only functionality that can't easily be tested in automated server tests.

**Comment by justincy** [comment]
getSourceRefsQuery is tested here: https://github.com/FamilySearch/familysearch-javascript-sdk/blob/master/test/unit/sourcesSpec.js#L129-L156

Your use case is slightly different than the test. You're calling it from a source description which merely passes the URL to the `getSourceRefsQuery` method of the client. In your case the URL happens to not exist in the description that you have. 

You can see in the example requests and responses on the developer's site that [reading a source description directly](https://familysearch.org/developers/docs/api/sources/Read_Source_Description_usecase) will provide the `source-references-query` link but it's not returned in the [sources query response](https://familysearch.org/developers/docs/api/tree/Read_Person_Sources_usecase) (which is where you're getting the description). You can ask the API team to add the link in the sources query response if you think it should be there. Until then you'll have to read the source description to get the link. Like this:

```js
fsApi.getSourceDescription(sourceDescription.getSourceDescriptionUrl()).then(function(response){
    var description = response.getSourceDescription();
    // The description should now have the link we need
    description.getSourceRefsQuery();
});
```

Does that make sense?

**Comment by stanben** [comment]
So what you are saying is the response.getSourceDescriptions() method returns an array of incomplete source descriptions whereas response.getSourceDescription() returns a complete source description as defined in http://familysearch.github.io/familysearch-javascript-sdk/2.4/#/api/sources.types:constructor.SourceDescription ?   If both these methods reference the same documented sourceDescription then shouldn't the returned sourceDescriptions be the same?  If not then shouldn't the Javascript SDK API documentation refer to two different sourceDescription objects (which creates a more messy API)?

**Comment by justincy** [comment]
> So what you are saying is the response.getSourceDescriptions() method returns an array of incomplete source descriptions whereas response.getSourceDescription() returns a complete source description

No. The difference is not caused by the methods on the response object. The API itself is returning different data. The [sources query resource](https://familysearch.org/developers/docs/api/tree/Read_Person_Sources_usecase) does not include the `source-references-query` link in source descriptions.

The API is designed around the principles of [HATEOAS](https://familysearch.org/developers/docs/guides/HATEOASstates) and [Hypermedia](https://familysearch.org/developers/docs/guides/hypermedia). The basic idea is that there are a limited set of entry points into the ecosystem and a limited set of paths for traversing the data. [Collections](https://familysearch.org/developers/docs/guides/collections) describe the entry points; links in the returned data describe additional paths between objects.

In this case, the API has not considered a need for requesting all source references (attachments) of a source description which was just returned from a sources query and thus already has at least one known attachment. Your use case was not anticipated. But you can request for that link to be added.

For my personal curiosity, could you explain what you're attempting to do? You already know the source is attached to one person. Why are you asking for all other attachments? Are you trying to detect when a source is attached to multiple people?

**Comment by stanben** [comment]
One purpose is to simply understand the javascript API specifically dealing with sources.
The other is to see if there is a way to find all the people within familysearch that are attached to the same source from the perspective of the source. For example if the source is a census record, then who are all the people within family search that are attached to that census record. Currently, I have to go to the sources of each individual person and then identify the sources which are common between these people.  I am putting a demo app together so that I can go to familysearch and show them what is needed in source evaluation/research.  I would be happy to show you what I have currently so you can get an idea of what I am doing.

It seems the javascript API should reflect the principles and paths as you described. In other words if there are documented convenience methods for a response  then shouldn't the methods work as documented in the javascript API?  Example: in the javascript API documentation:
    1. SourceDescription is documented as a "type in module sources".  
    2. getSourceRefsQuery() is a documented method for a SourceDescription
Therefore, all APIs which are documented to return a SourceDescription or SourceDescription[] should support the documented methods defined for a SourceDescription.  If not then SourceDescription should be broken up into different modules within the API to indicate which module (eg. method subset) is actually being returned by the API.   If the underlying implementation is different than what is defined by the API, then the API is faulty is it not?

**Comment by justincy** [comment]
I think we're using some key words differently which is confusing us.

What you call the JavaScript API is what I call the JavaScript SDK; I never refer to it as the API. What I call the API is the REST API documented at https://familysearch.org/developers/docs/api/resources.

I created a working example of what you're trying to do at http://jsfiddle.net/cothxy54/1/. Login with your sandbox username and password. It takes about 30 seconds to run after you've logged in. When it's done it will print formatted JSON below the "Run" link.

**Comment by stanben** [comment]
Thank you very much.  I can now successfully execute getSourceRefsQuery()
from your example.  It appears that this method is useful to determine if
more than one person in familySearch has the same sourceReference attached
to their record, which could identify that the same "source" person has
been attached to more than one person within the family tree?  This doesn't
appear to be useful for what I am trying to do,

What is the getCoupleSourceRefs and getChildAndParentsSourceRefs methods
for?  Can a source be attached to a couple relationship or a parent-child
relationship?

Sorry for using the incorrect terminology. Do you understand how it can be
confusing in the javascript SDK documentation where the convenience
functions to client.getSpourcesQuery: getSourceDescriptions (get an array
of SourceDescriptions
<http://familysearch.github.io/familysearch-javascript-sdk/2.4/#/api/sources.types:constructor.SourceDescription>
from
the response) and getSourceDescription ( get the SourceDescription
<http://familysearch.github.io/familysearch-javascript-sdk/2.4/#/api/sources.types:constructor.SourceDescription>
with
the specified source description id from the response) provide a link to
the same SourceDescription object as does client.getSourceDescription ( get
the SourceDescription
<http://familysearch.github.io/familysearch-javascript-sdk/2.4/#/api/sources.types:constructor.SourceDescription>
from
the response) and yet they do not return the same thing?  You have shown me
that I have to go from one SourceDescrition to get to the other one which I
would never have guessed.

While I am breaking the rules for my demo app, Is there any other link that
would help me construct the source information besides using the
description.getAbout() url?  When I click one of these url links within the
sources section on the familysearch person page for example:
https://familysearch.org/pal:/MM9.1.1/XHDP_NSW
It redirects to the location:
https://familysearch.org/pal:/MM9.1.1/XHDP-NSW?treeref=KWHX-CBB%3Bhttps%3A%2F%2Ffamilysearch.org%2Ftree%2F%23view%3Dancestor%26person%3DKWHX-CBB&from=lynx1
This page shows the information for all the related people within this
source (CENSUS in this case) including people in the source record that
have not been attached to anyone within familysearch (Obviously a lot
happening behind the scenes). I can capture all of the information for
people listed on this source page that are actually attached to someone
within familysearch but miss capturing some of the information on this page
(like age and birth location) in the case of people listed on this page
that are not attached (could be because they are living or just haven't
been attached).
If you don't feel comfortable in helping me with this part, I understand.

Again, thank you for your very valuable help!

**Comment by justincy** [comment]
For your use case the [`getSourceAttachments`](http://familysearch.github.io/familysearch-javascript-sdk/2.4/#/api/sources.functions:getSourceAttachments) method will be helpful. It will query source references based on the `about` URL instead of being limited to the source description.

> Can a source be attached to a couple relationship or a parent-child
> relationship?

Yes.

> and yet they do not return the same thing?  You have shown me
> that I have to go from one SourceDescrition to get to the other one which I
> would never have guessed.

The behavior of the SDK reflects the behavior of the API. I agree that it can be confusing be it's not likely to change. There's no value in the SDK having a `SourceDescription` class and a `SourceDescriptionMissingMostLinks` class. Links are secondary to the data model. The primary data about the source description is the same.

One change that could be made in the SDK is for it to detect and throw an error when a necessary link is missing.

**Comment by stanben** [comment]
Is the about url the url which I pass to getSourceAttachments?

**Comment by justincy** [comment]
In your case, yes, but in general you can pass any URL to it to see if the URL has been attached to anything in the tree.

**Comment by stanben** [comment]
Since the "about url" is a normally one to one match between a person in
the tree and a person in a source all getSourceAttachments will give me is
the person that I already know about (and possibly someone else in the tree
that is also attached to the same person in the source).  What I need to
get is who are all of the people in the source which is a list of all the
 "about urls" for an entire source.  Do you know how to get that?  I have
not been able to find an entire source specific url but only the "about
url" for one person in the source.

**Comment by justincy** [comment]
Oh, I see. There is nothing in the public API that can help you with that.
