### ISSUE TITLE
How to catch get errors like 404

### ISSUE THREAD

**Issue by DebbieHoltzendorff** [FamilySearch/familysearch-javascript-sdk#149]
I am using JavaScript SDK 1 and am trying to catch errors when I look for a person but have a bad Id.
 
FamilySearch.getPerson(pid)
.then(function (response) {...}) 
.fail(function(e){ output('Got Person error:'.getStatusCode(e)); });
 
The getStatusCode doesn’t work. Any ideas on to capture the system error message on failure?

**Comment by justincy** [comment]
It looks like you're using jQuery, correct? That means the `fail` callback will be passed three parameters, `( jqXHR jqXHR, String textStatus, String errorThrown )`, as explained on the [jQuery.ajax()](http://api.jquery.com/jquery.ajax/) page. One of those three will have what you want.
