### ISSUE TITLE
Incorrect auth URLs for Sandbox and Integration references

### ISSUE THREAD

**Issue by misbach** [FamilySearch/familysearch-javascript-sdk#156]
The /src/global.js file doesn't have the "integration" reference listed. It also has the incorrect URL for the sandbox authentication endpoint. it should be "https://identint.familysearch.org/cis-web/oauth2/v3".

https://github.com/FamilySearch/familysearch-javascript-sdk/blob/master/src/globals.js#L30

**Comment by justincy** [comment]
I thought `integration` was just an alias for `sandbox`, or the other way around. Aren't they the same?

**Comment by misbach** [comment]
Yes, they share the same CIS DB, but for some reason the sub domain has to be `identint`. The `sandbox` subdomain will not work for authentication.

**Comment by jimmyz** [comment]
To clarify, "sandbox.familysearch.org" and "integration.familysearch.org" are setup to reverse proxy `/cis-web` to the identint.familysearch.org systems and will work for authentication in most cases. However, there are some OAuth configurations that break if the domain isn't set as "identint.familysearch.org".

Notice that the beta and production environments are setup such that:

Beta: identbeta.familysearch.org
Production: ident.familysearch.org

So, Integration should map to: identint.familysearch.org

**Comment by justincy** [comment]
Okay, that's good to know. I was just about to say that the current setup works here: http://jsfiddle.net/fqn6j7fs/44/

**Comment by dovy** [comment]
Pushing a new version with that fix, or monkey patching for me?  :P

**Comment by stoicflame** [comment]
Hey, how did Github know to close this issue with your commit? I've mentioned issues in my commit messages before. Is the magic incantation "closes #blah"? How did you know about that?

**Comment by justincy** [comment]
I just pushed a new version. It could take a little while for the CDNs to
pick it up but you can download it straight from the gh pages.

**Comment by justincy** [comment]
@stoicflame https://help.github.com/articles/closing-issues-via-commit-messages/
