### ISSUE TITLE
NPM not updating

### ISSUE THREAD

**Issue by justincy** [FamilySearch/familysearch-javascript-sdk#157]
Presumable it's failing because of this message:

> NPM API key format changed recently. If your deployment fails, check your API key in ~/.npmrc.

Our key is stored in `travis.yml`

**Comment by justincy** [comment]
@jimmyz You'll have to look into this. I don't have access to the devsupport npm account and I believe you set this up the first time around. See https://travis-ci.org/FamilySearch/familysearch-javascript-sdk/jobs/136554767#L444

**Comment by jimmyz** [comment]
Okay, I just sent a pull request. I believe the new key format is correct and it should address the issue. Let me know if it doesn't. The instructions were a little bit vague as to whether or not I needed to include the whole line: `//registry.npmjs.org/:_authToken=YOUR_API_KEY` or just the `YOUR_API_KEY` section. I guessed on the `YOUR_API_KEY`.
