### ISSUE TITLE
How to retrieve subsequent pages of result with context?

### ISSUE THREAD

**Issue by DebbieHoltzendorff** [FamilySearch/familysearch-javascript-sdk#167]
I'm using getPersonSearch which returns only 15 people and a parm called context. Docs say:
context - the search context token, which is returned from search requests and allows requests for subsequent pages

So how do I use context to get the additional people in my result?
Like:

``` js
        fsClient.getPersonSearch({
                    context: theContext
                })
                .then(function (response) {
```

does not work!
Is this documented anywhere?
Thanks,
Debbie Holtzendorff

**Comment by justincy** [comment]
You're doing it the correct way. When you say it doesn't work, what happens?

**Comment by DebbieHoltzendorff** [comment]
I found the above only returns the first 15 items over and over again. After some creative suffering I discover that I needed to add the index of the next 15 items desired like:
fsClient.getPersonSearch({
                    context: theContext
                    Index: theIndex // Previously calculated item number to start with
                })
                .then(function (response) {
Is there any documetation out there?
Thanks.

**Comment by justincy** [comment]
@DebbieHoltzendorff That actually makes some sense.

The only docs we have are http://familysearch.github.io/familysearch-javascript-sdk/2.5/#/api/searchAndMatch.functions:getPersonSearch and https://familysearch.org/developers/docs/api/tree/Person_Search_resource
