### ISSUE TITLE
Support options parameter for getPerson()

### ISSUE THREAD

**Issue by justincy** [FamilySearch/familysearch-javascript-sdk#169]
The [Person resource](https://familysearch.org/developers/docs/api/tree/Person_resource) supports query params but the SDK doesn't. Options will be required for apps that are currently using `persons-with-relationships?persons=true` to get a person, their relationships, and person objects for all relatives. Beginning in December, you will need to call the Person resources with `relatives=true` to get the same data; persons-with-relationships will return a 301.

**Comment by dovy** [comment]
Can't we put a fallback in?

**Comment by justincy** [comment]
Perhaps. What are you thinking?

**Comment by dovy** [comment]
Code for the new standard, console alert warning to switch. That way things don't break. ;)

**Comment by justincy** [comment]
Persons with relationships will return a 301 redirect to the person
resource with the proper query params so that things don't break.

**Comment by dovy** [comment]
Misread! Perhaps a console message might be good to inform anyways?

**Comment by justincy** [comment]
bd5d2240edaf15d87c82fe3c9e0cb70e988604d9

**Comment by justincy** [comment]
params are supported for the `getPerson()` method in v2.8 and up.
