### ISSUE TITLE
Improper information returning from getSpouses() request on a person.

### ISSUE THREAD

**Issue by calvinMcM** [FamilySearch/familysearch-javascript-sdk#175]
The following example request sequence is returning improper information:

1) FamilySearchSDK.getPerson(pid) - Makes the request. On successful fulfillment of the request:
2) response.getSpouses() - should return the spouses for the returned individual (as per the SDK documentation. Instead, it seems to be returning all of the person's spouses, their father, and (most of) their male children.

Supposedly this reflects a change in the FamilySearch API release that occurred in December that has not yet been accounted for. The bug is interfering terribly with at least one partner app (virtual-pedigree.fhtl.byu.edu).

Calvin McMurray
BYU Family History Technology Lab
fhtlab@gmail.com

**Comment by misbach** [comment]
@calvinMcM 

Thanks for the bug report. We will get this fixed, however I can't give you an estimate on when we will release a new version of the SDK.

FYI: The bug is on the following line if you want to quickly fix it yourself.
https://github.com/FamilySearch/familysearch-javascript-sdk/blob/f729e58a9e19675dce3647f591ef5b7f43715659/src/modules/persons.js#L205

**Comment by justincy** [comment]
@calvinMcM Could you provide me with a sample PID that this bug occurs with?

**Comment by justincy** [comment]
@calvinMcM Also, which version of the SDK are you using?

**Comment by calvinMcM** [comment]
The problem exists using my PIC KWFK-99P. As for SDK version, we are
currently using version 2.8.2

**Comment by justincy** [comment]
I can't access your PID because you're living and therefore your profile is private. Do you have an example of a deceased person?

**Comment by jimmyz** [comment]
MFYR-RQD should have 3 duplicates, but we're getting 5 spouses (2 are his father).

Ann
Ann
John Crundall
John Crondall
Ann Osborne

(ignore the duplication)

**Comment by calvinMcM** [comment]
LHG7-2BQ is the pid for one of my deceasedfemale ancestors. She has a known
father and at least one son to help illustrate the point.

**Comment by justincy** [comment]
@jimmyz @calvinMcM You must be using the `relatives` parameter. Is that correct? It appears to be adding extra relationships in the response which breaks assumptions made by the code. I didn't know the `relatives` parameter did that which is why it took so long for me to verify what you were seeing.

**Comment by justincy** [comment]
This is fixed in v2.10.0

**Comment by calvinMcM** [comment]
From what I can see, v2.10.0 isn't supported via CDN - it only ships as a NodeJS module. If so, it would only be useful if all of the requests to FamilySearch are being made from the server instead of from client-side code, which is how Virtual Pedigree uses it, nor several other apps I know of. If the problem has already been resolved in 2.10.0, would it be possible to get that version released through your regular CDN's to allow clients to make use of the updated version?

**Comment by calvinMcM** [comment]
I left a note on Github about a CDN release of the 2.10.0 version of the
SDK. In the interim, were working on building the node moduleseparately and
using that. Thanks for all of your help!

**Comment by justincy** [comment]
https://unpkg.com/familysearch-javascript-sdk@2.10.0/dist/familysearch-javascript-sdk.min.js

**Comment by calvinMcM** [comment]
Thanks. That should make things easier. Did I just miss the link to that
somewhere?

**Comment by justincy** [comment]
It's in the README.
