### ISSUE TITLE
Firefox Support - Headers.prototype.getAll method has been removed

### ISSUE THREAD

**Issue by dovy** [FamilySearch/familysearch-javascript-sdk#177]
```The Headers.prototype.getAll method has been removed as per the latest Fetch spec. Instead, the Headers.prototype.get method now returns the all values of a given HTTP header in a comma-separated string instead of just the first value.```

https://www.fxsitecompat.com/en-CA/docs/2016/headers-getall-has-been-removed-in-favour-of-get-now-returning-all-values/

Need to use Headers.get() instead.

**Comment by dovy** [comment]
Solution:

https://github.com/FamilySearch/familysearch-javascript-sdk/blob/6d7b1b0b4c18cbeed405f56a18ddc342c6451f2d/src/plumbing.js#L317

```
try {
    return all === true ? response.headers.getAll(header) : response.headers.get(header);
} catch(err) { // Firefox shim
    return all === true ? response.headers.get() : response.headers.get(header);
}
```

**Comment by stoicflame** [comment]
Wait a minute...

Are you saying that Firefox doesn't maintain full backwards compatibility forever? Seriously, getting a little annoyed here. Don't you think they should provide some parameter we can pass to revert to the old FF 51 behavior?

😉 Just teasing, @dovy.

**Comment by dovy** [comment]
I agree and i think it's totally unacceptable. Remember, they're not the best nowadays. I haven't used them for 3 years.  ;)

**Comment by dovy** [comment]
But this is more of a standard change and FireFox is just being more proactive than others.

**Comment by stoicflame** [comment]
😃 Yes. Of course.

**Comment by justincy** [comment]
@dovy I'm curious what your usecase for using the `all` parameter of the `getHeaders()` method. The SDK never uses it.

I believe that an easier fix would be to deprecate and ignore the `all` parameter.

**Comment by dovy** [comment]
I wasn't using it. It's in the piping and firefox was shooting errors when checking for attaching a source to a person. It checks the header to ensure that it's been given a "created" header, than then move forward. This was failing in firefox and causing my app to just freeze with a JS error.

**Comment by justincy** [comment]
I was wrong about the `all` parameter it not being used in the SDK: https://github.com/FamilySearch/familysearch-javascript-sdk/blob/13a386f41cc469eeb9119689c47d6c952e63ba78/src/classes/base.js#L173

I think we can just update that one internal usage and call it good.
