### ISSUE TITLE
Ship with built-in HTTP and deferred libraries

### ISSUE THREAD

**Issue by justincy** [FamilySearch/familysearch-javascript-sdk#85]
The advantage to this is it simplifies both the configuration needed when using the SDK as well as the internal code that manages the different libs we support.

For HTTP, [SuperAgent](https://github.com/visionmedia/superagent) is a lightweight http library that works both in node and the browser.

Don't __need__ to do this, especially if it bloats the build too much.

You could say that it would make testing more difficult in angular because it breaks the angular idea of mocks, but it's difficult to build mocks for the SDK already. You have to know what API the un-documented internal wrappers expect. And then you have to figure out how the SDK init code guesses which wrapper it should use.

**Comment by justincy** [comment]
This would make the documentation a lot easier too.

**Comment by redbugz** [comment]
Requires a few browser polyfills, and I haven't had a chance to really test it out yet, but another consideration might be an isomorphic http fetcher like https://www.npmjs.com/package/isomorphic-fetch

**Comment by justincy** [comment]
@redbugz Thanks. That looks nice.

**Comment by justincy** [comment]
If we did this it would mostly affect people who use Angular. Because we wouldn't be using the angular `$http` and `$q` services anymore, users would have to begin using `$scope.apply()` to notify angular of updates. 

The sdk exposes it's internal [http](http://familysearch.github.io/familysearch-javascript-sdk/#/api/plumbing.functions:http) method so theoretically angular users could monkey patch the sdk to intercept all responses and call `$scope.apply()` in one place, but I don't know if that would actually work. Something like this:

```js
var originalHttp = FamilySearch.prototype.http;
FamilySearch.prototype.http = function(){
    var promise = originalHttp.apply(this, arguments);
    promise.then(function(){
        $scope.apply();
    });
    return promise;
};
```

**Comment by justincy** [comment]
Anybody relying on [unique promise interfaces](http://familysearch.github.io/familysearch-javascript-sdk/#/api#sdk-functions-return-promises) would be affected too.

**Comment by justincy** [comment]
Another advantage to doing this is that we can support [promise chaining](http://www.html5rocks.com/en/tutorials/es6/promises/#toc-chaining) both internally and for the promises that are returned. jQuery Deferreds/Promises [don't support it](https://thewayofcode.wordpress.com/tag/jquery-deferred-broken/).

**Comment by justincy** [comment]
We'll likely remove the `timeout_function` option too.
