### ISSUE TITLE
Get rid of $ prefix on object methods

### ISSUE THREAD

**Issue by justincy** [FamilySearch/familysearch-javascript-sdk#92]
The `$` prefix is used to namespace object methods because the real data is stored at the first level. If we stored the underlying data in a `_data` property then we wouldn't have to worry about method names conflicting with the data model's properties.

**Comment by dovy** [comment]
Good call. There's a mix of $. prefixed and non-prefixed methods.

**Comment by justincy** [comment]
There is actually a clear rule for when the `$` prefix is used. In general, there are three types of methods:

1. SDK methods `sdk.getPerson()`
2. Response methods `response.getChanges()`
3. Object methods `person.$getBirthDate()`

The `$` prefix is only used on object methods for the sake of namespacing to avoid collisions with the object data, as explained above. Despite there being a rule, it's still confusing. It took me a lot of time to recognize the rule and stop making mistakes with using the prefix when I shouldn't or not using it when I should.

Besides making the SDK easier to use, removing the prefix would make the code easier to maintain. It's not so much the prefix that is the problem but the reason why the prefix is used. The fact that the data is stored at the top level makes initializing, serializing, and refreshing more difficult. Separating the raw data from the methods and other object data will make the previously mentioned tasks much easier.

This will be a pretty significant change to the code base but the breaking changes are minor in the sense that theoretically you just have to remove the `$` (it won't be quite as easy for anybody using jQuery or any other library that also makes frequent use of the `$`).

**Comment by justincy** [comment]
I forgot one critical point: most classes have a documented set of properties that can be directly accessed. For example, the [User](http://familysearch.github.io/familysearch-javascript-sdk/#/api/user.types:constructor.User) class has 10 properties and no methods. If we made this change we would have to add 10 get methods for those properties. That would be a significant breaking change.
