### ISSUE TITLE
Fix jsFiddles that rely on prettyPrint

### ISSUE THREAD

**Issue by justincy** [FamilySearch/familysearch-javascript-sdk#98]
Some jsFiddles (don't know how many) rely on a prettyPrint library that was hosted at `http://public.werelate.org/prettyprint.js`. That now returns a 403 which breaks any jsFiddle that relies on it.

**Comment by jimmyz** [comment]
Looks like the prettyprint.js library that was being used is this one: https://github.com/padolsey-archive/prettyprint.js

I wonder if there is a CDN hosting this somewhere.

**Comment by jimmyz** [comment]
http://james.padolsey.com/javascript/prettyprint-for-javascript/

**Comment by justincy** [comment]
It's not on any CDN that I could find. Let's use [RawGit](http://rawgit.com/) for now. The jsFiddles traffic will be very light.
