### ISSUE TITLE
Date Authority - Split dates in the iterum?

### ISSUE THREAD

**Issue by dovy** [FamilySearch/familysearch-javascript-sdk#99]
While we're waiting for the key/value pair to be sorted, should we check for a forward slash in the text and split into two entries within the SDK? We can always look for the key/value header pair and if there's more than 1, skip.

Thoughts @jimmyz @justincy

**Comment by justincy** [comment]
This is in regards to the [first bug listed here](https://groups.google.com/a/ldsmail.net/d/msg/fsdn/hJMA8gHSkm8/G2dyNsYK7AQJ) that causes `1-7-1900` to be returned in the normalized form `1 July 1900 / 7 January 1900`.

**Comment by jimmyz** [comment]
I believe the bug will be addressed pretty quickly in the API and that it would be better to not add additional logic to the SDK to compensate for the bug.

**Comment by justincy** [comment]
I agree with @jimmyz if it does get fixed quickly.

@dovy Until it gets fixed I recommend splitting it yourself.

**Comment by dovy** [comment]
Oy, fine. heh.
